export const IMPACT_WEIGHTS = {
  SEVERITY: 0.25,
  POPULATION: 0.20,
  DURATION: 0.15,
  CONCENTRATION: 0.15,
  CRITICAL_FACILITY: 0.10,
  RECURRENCE: 0.10,
  EVIDENCE: 0.05
} as const;

export const IMPACT_MAX_SCORES = {
  SEVERITY: 25,
  POPULATION: 20,
  DURATION: 15,
  CONCENTRATION: 15,
  CRITICAL_FACILITY: 10,
  RECURRENCE: 10,
  EVIDENCE: 5
} as const;

export const IMPACT_THRESHOLDS = {
  LOW_MAX: 39,
  MEDIUM_MAX: 64,
  HIGH_MAX: 84,
  CRITICAL_MIN: 85
} as const;

export const SIMILARITY_THRESHOLDS = {
  STRONG_DUPLICATE: 0.85,
  RELATED_CANDIDATE: 0.70
} as const;
